### ISSUE TITLE
Import failure in py27

### ISSUE THREAD

**Issue by nehaljwani** [pjdelport/backports.test.support#3]
```
(test) [root@centos7-nwani ~]# python
Python 2.7.14 |Anaconda, Inc.| (default, Dec  7 2017, 17:05:42) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import backports.test.support
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/test/lib/python2.7/site-packages/backports/test/support/__init__.py", line 745, in <module>
    IPV6_ENABLED = _is_ipv6_enabled()
  File "/opt/conda/envs/test/lib/python2.7/site-packages/backports/test/support/__init__.py", line 736, in _is_ipv6_enabled
    sock.bind((HOSTv6, 0))
  File "/opt/conda/envs/test/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
```

**Comment by PiDelport** [comment]
Good catch!

The root cause of this is PEP 3151, introduced in Python 3.3:

* [PEP 3151 – Reworking the OS and IO exception hierarchy
](https://www.python.org/dev/peps/pep-3151/)
* [Python 3.3 release notes](https://docs.python.org/3/whatsnew/3.3.html#pep-3151-reworking-the-os-and-io-exception-hierarchy)
